apiVersion: v1
kind: Namespace
metadata:
  name: devops-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devops-operator-role
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devops-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devops-operator-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: devops-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: mutator
  name: devops-mutator
  namespace: devops-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: mutator
  template:
    metadata:
      labels:
        control-plane: mutator
    spec:
      containers:
        - image: 364554757/devops:v0.1.2
          args:
            - server
            - --leader-election=true
          name: mutator
          resources:
            limits:
              cpu: 2000m
              memory: 3000Mi
      terminationGracePeriodSeconds: 10
      serviceAccountName: default

